project_name: hasher
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: hasher
    ldflags:
      - -s -w
      - -X github.com/little-forest/{{.ProjectName}}/cmd.version={{.Version}}
      - -X github.com/little-forest/{{.ProjectName}}/cmd.revision={{.ShortCommit}}
      - -X github.com/little-forest/{{.ProjectName}}/cmd.date={{.Date}}
      - -X github.com/little-forest/{{.ProjectName}}/cmd.osArch={{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
