project_name: hasher
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: hasher
    ldflags:
      - -s -w
      - -X github.com/little-forest/hasher/cmd.version={{. Version}}
      - -X github.com/little-forest/hasher/cmd.revision={{. ShortCommit}}
      - -X github.com/little-forest/hasher/cmd.date={{. Date}}
      - -X github.com/little-forest/hasher/cmd.date={{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}
    env:
      - CGO_ENABLED=0
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto
