repos:
-   repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5 # change this to the latest version
    hooks:
    -   id: go-fmt
        args: ["-d"]
    -   id: go-mod-tidy
    -   id: golangci-lint-mod

