version: "2"

run:
  timeout: 10m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - misspell
  disable:
    - unused

  settings:
    govet:
      enable-all: true

issues:
  exclude-use-default: false

