name: Continuous integration

on:
 push:
   branches:
     # - 'main'
     - '**'
   paths:
     - src/**
     - .github/workflows/**
     - 'aqua.yaml'

 pull_request:
   paths:
     - src/**
     - .github/workflows/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: aquaproj/aqua-installer@v1.1.1
        with:
          aqua_version: v1.17.1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Version
        run: go version
 
