name: Continuous integration

on:
 push:
   branches:
     - 'main'
   paths:
     - src/**
     - .github/workflows/**
     - 'aqua.yaml'

 pull_request:
   paths:
     - src/**
     - .github/workflows/**
     - 'aqua.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: aquaproj/aqua-installer@v1.1.1
        with:
          aqua_version: v1.17.1

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      # - name: run GoLangCI-Lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     version: v1.48.0
      #     working-directory: ./src

      - name: Setup GoLangCI-Lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s 

      - name: Show GoLangCI-Lint version
        run: ./bin/golangci-lint --version | head -n1

      - name: Run GoLangCI-Lint
        run: >
          github-comment exec --token ${{ secrets.GITHUB_TOKEN }} --
          ../bin/golangci-lint run
        working-directory: ./src

      - name: Hide old comment
        run: github-comment hide --token ${{ secrets.GITHUB_TOKEN }}

      - name: Build 
        run: go build
        working-directory: ./src
 
