name: Continuous integration

on:
 push:
   branches:
     - 'main'
   paths:
     - src/**
     - .github/workflows/**
     - 'aqua.yaml'

 pull_request:
   paths:
     - src/**
     - .github/workflows/**
     - 'aqua.yaml'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: aquaproj/aqua-installer@v2.1.1
        with:
          aqua_version: v2.3.6

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Setup GoLangCI-Lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s 

      - name: Show GoLangCI-Lint version
        run: ./bin/golangci-lint --version | head -n1

      - name: Run GoLangCI-Lint
        run: >
          github-comment exec --token ${{ secrets.GITHUB_TOKEN }} --
          ../bin/golangci-lint run
        working-directory: ./src

      - name: Hide old comment
        run: github-comment hide --token ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'pull_request' || ( github.event_name == 'push' && github.ref_name != 'main' ) }}

      - name: Build 
        run: go build
        working-directory: ./src
 
      - name: Test
        run: go test -v ./...
        working-directory: ./src
