name: Continuous integration

on:
  push:
    branches:
      - 'main'
    paths:
      - src/**
      - .github/workflows/**
      - version
  pull_request:
    paths:
      - src/**
      - .github/workflows/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
        run: go version
 
