name: Continuous integration

on:
 push:
   branches:
     - 'main'
   paths:
     - src/**
     - .github/workflows/**
     - 'aqua.yaml'

 pull_request:
   paths:
     - src/**
     - .github/workflows/**
     - 'aqua.yaml'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: aquaproj/aqua-installer@v3.0.0
        with:
          aqua_version: v2.27.0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'

      - name: Setup GoLangCI-Lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s 

      - name: Show GoLangCI-Lint version
        run: ./bin/golangci-lint --version | head -n1

      - name: Run GoLangCI-Lint
        run: >
          github-comment exec --token ${{ secrets.GITHUB_TOKEN }} --
          ../bin/golangci-lint run
        working-directory: ./src

      - name: Hide old comment
        run: github-comment hide --token ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.event_name == 'pull_request' || ( github.event_name == 'push' && github.ref_name != 'main' ) }}

      - name: Build 
        run: go build
        working-directory: ./src
 
      - name: Test
        run: go test -v ./...
        working-directory: ./src
